[phases.setup]
pkgs = ["nodejs_22", "pnpm-9_x"]

[phases.install]
cmds = [
	"pnpm install --no-frozen-lockfile --prod=false --filter @workspace/api-server..."
]

[phases.build]
cmds = ["pnpm --filter @workspace/api-server build"]

[buildkit]
prune = true
