// Seed script: cadastra todos os bairros motoboy (Santo André, SBC, São Paulo)
// Uso: DATABASE_URL=<url> pnpm tsx scripts/src/seed-motoboy-neighborhoods.ts

import { db, motoboyNeighborhoodsTable } from "../../lib/db/src/index";
import crypto from "crypto";

interface Entry { neighborhood: string; city: string; price: number; sortOrder: number; }

const entries: Entry[] = [
  // ── Santo André ────────────────────────────────────────────────────────────
  { neighborhood: "Centro",                  city: "Santo André", price: 70, sortOrder: 1  },
  { neighborhood: "Vila Assunção",           city: "Santo André", price: 70, sortOrder: 2  },
  { neighborhood: "Campestre",               city: "Santo André", price: 70, sortOrder: 3  },
  { neighborhood: "Paraíso",                 city: "Santo André", price: 70, sortOrder: 4  },
  { neighborhood: "Vila Gilda",              city: "Santo André", price: 75, sortOrder: 5  },
  { neighborhood: "Santa Terezinha",         city: "Santo André", price: 75, sortOrder: 6  },
  { neighborhood: "Bangu",                   city: "Santo André", price: 75, sortOrder: 7  },
  { neighborhood: "Parque das Nações",       city: "Santo André", price: 75, sortOrder: 8  },
  { neighborhood: "Jardim do Estádio",       city: "Santo André", price: 75, sortOrder: 9  },
  { neighborhood: "Vila Luzita",             city: "Santo André", price: 80, sortOrder: 10 },
  { neighborhood: "Jardim Belval",           city: "Santo André", price: 80, sortOrder: 11 },
  { neighborhood: "Vila Valparaíso",         city: "Santo André", price: 80, sortOrder: 12 },
  { neighborhood: "Parque Erasmo Assunção",  city: "Santo André", price: 80, sortOrder: 13 },
  { neighborhood: "Jardim Santo Alberto",    city: "Santo André", price: 80, sortOrder: 14 },
  { neighborhood: "Jardim Ana Maria",        city: "Santo André", price: 80, sortOrder: 15 },
  { neighborhood: "Sítio dos Vianas",        city: "Santo André", price: 80, sortOrder: 16 },
  { neighborhood: "Vila Pires",              city: "Santo André", price: 80, sortOrder: 17 },
  { neighborhood: "Parque Capuava",          city: "Santo André", price: 85, sortOrder: 18 },
  { neighborhood: "Vila Palmares",           city: "Santo André", price: 85, sortOrder: 19 },
  { neighborhood: "Jardim Alvorada",         city: "Santo André", price: 85, sortOrder: 20 },
  { neighborhood: "Parque Miami",            city: "Santo André", price: 85, sortOrder: 21 },
  { neighborhood: "Jardim Cristianópolis",   city: "Santo André", price: 85, sortOrder: 22 },
  { neighborhood: "Jardim do Estádio",       city: "Santo André", price: 85, sortOrder: 23 },
  { neighborhood: "Vila Curuçá",             city: "Santo André", price: 85, sortOrder: 24 },
  { neighborhood: "Jardim Ipanema",          city: "Santo André", price: 85, sortOrder: 25 },
  { neighborhood: "Jardim Utinga",           city: "Santo André", price: 85, sortOrder: 26 },
  { neighborhood: "Jardim Alvorada",         city: "Santo André", price: 90, sortOrder: 27 },
  { neighborhood: "Jardim Santo André",      city: "Santo André", price: 90, sortOrder: 28 },
  { neighborhood: "Parque Jaçatuba",         city: "Santo André", price: 90, sortOrder: 29 },
  { neighborhood: "Recanto da Natureza",     city: "Santo André", price: 90, sortOrder: 30 },
  { neighborhood: "Rio Grande da Serra",     city: "Santo André", price: 90, sortOrder: 31 },

  // ── São Bernardo do Campo ──────────────────────────────────────────────────
  { neighborhood: "Rudge Ramos",       city: "São Bernardo do Campo", price: 75,  sortOrder: 1  },
  { neighborhood: "Anchieta",          city: "São Bernardo do Campo", price: 75,  sortOrder: 2  },
  { neighborhood: "Jardim do Mar",     city: "São Bernardo do Campo", price: 80,  sortOrder: 3  },
  { neighborhood: "Centro",            city: "São Bernardo do Campo", price: 80,  sortOrder: 4  },
  { neighborhood: "Baeta Neves",       city: "São Bernardo do Campo", price: 80,  sortOrder: 5  },
  { neighborhood: "Nova Petrópolis",   city: "São Bernardo do Campo", price: 85,  sortOrder: 6  },
  { neighborhood: "Assunção",          city: "São Bernardo do Campo", price: 85,  sortOrder: 7  },
  { neighborhood: "Planalto",          city: "São Bernardo do Campo", price: 90,  sortOrder: 8  },
  { neighborhood: "Demarchi",          city: "São Bernardo do Campo", price: 90,  sortOrder: 9  },
  { neighborhood: "Ferrazópolis",      city: "São Bernardo do Campo", price: 90,  sortOrder: 10 },
  { neighborhood: "Alves Dias",        city: "São Bernardo do Campo", price: 95,  sortOrder: 11 },
  { neighborhood: "Dos Casa",          city: "São Bernardo do Campo", price: 95,  sortOrder: 12 },
  { neighborhood: "Cooperativa",       city: "São Bernardo do Campo", price: 100, sortOrder: 13 },
  { neighborhood: "Alvarenga",         city: "São Bernardo do Campo", price: 100, sortOrder: 14 },
  { neighborhood: "Montanhão",         city: "São Bernardo do Campo", price: 105, sortOrder: 15 },
  { neighborhood: "Tatetos",           city: "São Bernardo do Campo", price: 105, sortOrder: 16 },
  { neighborhood: "Batistini",         city: "São Bernardo do Campo", price: 110, sortOrder: 17 },
  { neighborhood: "Pós-Balsa",         city: "São Bernardo do Campo", price: 110, sortOrder: 18 },

  // ── São Paulo ──────────────────────────────────────────────────────────────
  { neighborhood: "Água Rasa",            city: "São Paulo", price: 60,  sortOrder: 1  },
  { neighborhood: "Aricanduva",           city: "São Paulo", price: 70,  sortOrder: 2  },
  { neighborhood: "Arthur Alvim",         city: "São Paulo", price: 75,  sortOrder: 3  },
  { neighborhood: "Alto de Pinheiros",    city: "São Paulo", price: 65,  sortOrder: 4  },
  { neighborhood: "Anhanguera",           city: "São Paulo", price: 90,  sortOrder: 5  },
  { neighborhood: "Barra Funda",          city: "São Paulo", price: 50,  sortOrder: 6  },
  { neighborhood: "Bela Vista",           city: "São Paulo", price: 50,  sortOrder: 7  },
  { neighborhood: "Bom Retiro",           city: "São Paulo", price: 50,  sortOrder: 8  },
  { neighborhood: "Brás",                 city: "São Paulo", price: 50,  sortOrder: 9  },
  { neighborhood: "Belém",                city: "São Paulo", price: 70,  sortOrder: 10 },
  { neighborhood: "Brasilândia",          city: "São Paulo", price: 80,  sortOrder: 11 },
  { neighborhood: "Butantã",              city: "São Paulo", price: 75,  sortOrder: 12 },
  { neighborhood: "Consolação",           city: "São Paulo", price: 50,  sortOrder: 13 },
  { neighborhood: "Casa Verde",           city: "São Paulo", price: 60,  sortOrder: 14 },
  { neighborhood: "Cangaíba",             city: "São Paulo", price: 75,  sortOrder: 15 },
  { neighborhood: "Carrão",               city: "São Paulo", price: 70,  sortOrder: 16 },
  { neighborhood: "Cidade Líder",         city: "São Paulo", price: 75,  sortOrder: 17 },
  { neighborhood: "Cidade Tiradentes",    city: "São Paulo", price: 90,  sortOrder: 18 },
  { neighborhood: "Cambuci",              city: "São Paulo", price: 50,  sortOrder: 19 },
  { neighborhood: "Campo Belo",           city: "São Paulo", price: 65,  sortOrder: 20 },
  { neighborhood: "Campo Grande",         city: "São Paulo", price: 75,  sortOrder: 21 },
  { neighborhood: "Campo Limpo",          city: "São Paulo", price: 80,  sortOrder: 22 },
  { neighborhood: "Capão Redondo",        city: "São Paulo", price: 80,  sortOrder: 23 },
  { neighborhood: "Cidade Ademar",        city: "São Paulo", price: 75,  sortOrder: 24 },
  { neighborhood: "Cidade Dutra",         city: "São Paulo", price: 80,  sortOrder: 25 },
  { neighborhood: "Cursino",              city: "São Paulo", price: 65,  sortOrder: 26 },
  { neighborhood: "Cachoeirinha",         city: "São Paulo", price: 70,  sortOrder: 27 },
  { neighborhood: "Ermelino Matarazzo",   city: "São Paulo", price: 75,  sortOrder: 28 },
  { neighborhood: "Freguesia do Ó",       city: "São Paulo", price: 70,  sortOrder: 29 },
  { neighborhood: "Guaianazes",           city: "São Paulo", price: 90,  sortOrder: 30 },
  { neighborhood: "Grajaú",               city: "São Paulo", price: 90,  sortOrder: 31 },
  { neighborhood: "Iguatemi",             city: "São Paulo", price: 90,  sortOrder: 32 },
  { neighborhood: "Itaim Paulista",       city: "São Paulo", price: 90,  sortOrder: 33 },
  { neighborhood: "Itaquera",             city: "São Paulo", price: 80,  sortOrder: 34 },
  { neighborhood: "Ipiranga",             city: "São Paulo", price: 60,  sortOrder: 35 },
  { neighborhood: "Itaim Bibi",           city: "São Paulo", price: 65,  sortOrder: 36 },
  { neighborhood: "Jaçanã",               city: "São Paulo", price: 80,  sortOrder: 37 },
  { neighborhood: "Jardim Helena",        city: "São Paulo", price: 90,  sortOrder: 38 },
  { neighborhood: "José Bonifácio",       city: "São Paulo", price: 85,  sortOrder: 39 },
  { neighborhood: "Jabaquara",            city: "São Paulo", price: 65,  sortOrder: 40 },
  { neighborhood: "Jardim Ângela",        city: "São Paulo", price: 80,  sortOrder: 41 },
  { neighborhood: "Jardim Paulista",      city: "São Paulo", price: 65,  sortOrder: 42 },
  { neighborhood: "Jardim São Luís",      city: "São Paulo", price: 80,  sortOrder: 43 },
  { neighborhood: "Jaguará",              city: "São Paulo", price: 80,  sortOrder: 44 },
  { neighborhood: "Jaguaré",              city: "São Paulo", price: 80,  sortOrder: 45 },
  { neighborhood: "Jaraguá",              city: "São Paulo", price: 80,  sortOrder: 46 },
  { neighborhood: "Liberdade",            city: "São Paulo", price: 50,  sortOrder: 47 },
  { neighborhood: "Lajeado",              city: "São Paulo", price: 90,  sortOrder: 48 },
  { neighborhood: "Lapa",                 city: "São Paulo", price: 70,  sortOrder: 49 },
  { neighborhood: "Limão",                city: "São Paulo", price: 70,  sortOrder: 50 },
  { neighborhood: "Mandaqui",             city: "São Paulo", price: 75,  sortOrder: 51 },
  { neighborhood: "Mooca",                city: "São Paulo", price: 50,  sortOrder: 52 },
  { neighborhood: "Marsilac",             city: "São Paulo", price: 100, sortOrder: 53 },
  { neighborhood: "Moema",                city: "São Paulo", price: 65,  sortOrder: 54 },
  { neighborhood: "Morumbi",              city: "São Paulo", price: 70,  sortOrder: 55 },
  { neighborhood: "Pari",                 city: "São Paulo", price: 50,  sortOrder: 56 },
  { neighborhood: "Parque do Carmo",      city: "São Paulo", price: 80,  sortOrder: 57 },
  { neighborhood: "Penha",                city: "São Paulo", price: 70,  sortOrder: 58 },
  { neighborhood: "Ponte Rasa",           city: "São Paulo", price: 75,  sortOrder: 59 },
  { neighborhood: "Parelheiros",          city: "São Paulo", price: 95,  sortOrder: 60 },
  { neighborhood: "Pedreira",             city: "São Paulo", price: 80,  sortOrder: 61 },
  { neighborhood: "Perdizes",             city: "São Paulo", price: 65,  sortOrder: 62 },
  { neighborhood: "Perus",                city: "São Paulo", price: 90,  sortOrder: 63 },
  { neighborhood: "Pinheiros",            city: "São Paulo", price: 65,  sortOrder: 64 },
  { neighborhood: "Pirituba",             city: "São Paulo", price: 80,  sortOrder: 65 },
  { neighborhood: "República",            city: "São Paulo", price: 50,  sortOrder: 66 },
  { neighborhood: "Raposo Tavares",       city: "São Paulo", price: 80,  sortOrder: 67 },
  { neighborhood: "Rio Pequeno",          city: "São Paulo", price: 75,  sortOrder: 68 },
  { neighborhood: "Santa Cecília",        city: "São Paulo", price: 50,  sortOrder: 69 },
  { neighborhood: "Santana",              city: "São Paulo", price: 70,  sortOrder: 96 },
  { neighborhood: "Sé",                   city: "São Paulo", price: 50,  sortOrder: 70 },
  { neighborhood: "Sapopemba",            city: "São Paulo", price: 75,  sortOrder: 71 },
  { neighborhood: "São Lucas",            city: "São Paulo", price: 70,  sortOrder: 72 },
  { neighborhood: "São Mateus",           city: "São Paulo", price: 80,  sortOrder: 73 },
  { neighborhood: "São Miguel",           city: "São Paulo", price: 85,  sortOrder: 74 },
  { neighborhood: "São Rafael",           city: "São Paulo", price: 85,  sortOrder: 75 },
  { neighborhood: "Sacomã",               city: "São Paulo", price: 65,  sortOrder: 76 },
  { neighborhood: "Santo Amaro",          city: "São Paulo", price: 70,  sortOrder: 77 },
  { neighborhood: "Saúde",                city: "São Paulo", price: 65,  sortOrder: 78 },
  { neighborhood: "Socorro",              city: "São Paulo", price: 75,  sortOrder: 79 },
  { neighborhood: "São Domingos",         city: "São Paulo", price: 80,  sortOrder: 80 },
  { neighborhood: "Tremembé",             city: "São Paulo", price: 90,  sortOrder: 81 },
  { neighborhood: "Tucuruvi",             city: "São Paulo", price: 75,  sortOrder: 82 },
  { neighborhood: "Tatuapé",              city: "São Paulo", price: 65,  sortOrder: 83 },
  { neighborhood: "Vila Guilherme",       city: "São Paulo", price: 60,  sortOrder: 84 },
  { neighborhood: "Vila Maria",           city: "São Paulo", price: 65,  sortOrder: 85 },
  { neighborhood: "Vila Medeiros",        city: "São Paulo", price: 70,  sortOrder: 86 },
  { neighborhood: "Vila Curuçá",          city: "São Paulo", price: 90,  sortOrder: 87 },
  { neighborhood: "Vila Formosa",         city: "São Paulo", price: 70,  sortOrder: 88 },
  { neighborhood: "Vila Jacuí",           city: "São Paulo", price: 80,  sortOrder: 89 },
  { neighborhood: "Vila Matilde",         city: "São Paulo", price: 70,  sortOrder: 90 },
  { neighborhood: "Vila Prudente",        city: "São Paulo", price: 60,  sortOrder: 91 },
  { neighborhood: "Vila Andrade",         city: "São Paulo", price: 75,  sortOrder: 92 },
  { neighborhood: "Vila Mariana",         city: "São Paulo", price: 60,  sortOrder: 93 },
  { neighborhood: "Vila Sônia",           city: "São Paulo", price: 80,  sortOrder: 94 },
  { neighborhood: "Vila Leopoldina",      city: "São Paulo", price: 80,  sortOrder: 95 },
];

async function main() {
  console.log(`Inserindo ${entries.length} bairros...`);

  for (const e of entries) {
    const id = crypto.randomBytes(8).toString("hex");
    await db.insert(motoboyNeighborhoodsTable).values({
      id,
      neighborhoodName: e.neighborhood,
      city:             e.city,
      price:            String(e.price.toFixed(2)),
      sortOrder:        e.sortOrder,
      isActive:         true,
      notes:            null,
    });
    console.log(`  ✓ ${e.city} — ${e.neighborhood} — R$ ${e.price}`);
  }

  console.log(`\nPronto! ${entries.length} bairros cadastrados.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Erro:", err);
  process.exit(1);
});
