uploads = []
generated = []

[[outputs]]
id = "cc-glaMP-e_pMEAVxKq9d"
uri = "file://ka-imports-site.zip"
type = "unspecified"
title = "Clayton — Código-fonte completo (atualizado)"

[[outputs]]
id = "uL3cNZ3wsh-wzU9xhwPBF"
uri = "file://ka-imports-full.zip"
type = "unspecified"
title = "Clayton — Projeto completo (51 MB, sem node_modules)"
